### ISSUE TITLE
Locally caching functions in the file/function

### ISSUE THREAD

**Issue by Kefta** [MysteryPancake/GitHub-Rule-Book#10]
Ex. ```local string_len = string.len```

While it is overkill for most situations to cache global/library functions to the file, there are times were performance-sensitive code could need the functions localised. Read page 3 of this official Lua sample here: https://www.lua.org/gems/sample.pdf

Maybe make the case to only use it where necessary?

**Comment by MysteryPancake** [comment]
I knew about that sort of thing and I was using it on a lot of my code. A bit later in the thing I added this:

> `local var = var` mustn't be used unless in a module.

Because I just don't find it useful anymore to have slightly faster speed, because `local var = var` makes code look messy and confusing, and it relies on you remembering to update the references whenever you use any new function.

**Comment by MysteryPancake** [comment]
You were probably referring to that part anyway

**Comment by Kefta** [comment]
I believe the slightly messier code is worth the speed in specific cases. Ex. https://hastebin.com/gabumuyosu.swift

This code would be ~15-18% slower without the localisations if I remember my benchmarking correctly

**Comment by MysteryPancake** [comment]
I guess
https://github.com/MysteryPancake/Rule-Book/commit/4fa7bed7550d37b94a8061a4e4c9f9c79c031c42

**Comment by Kefta** [comment]
I would have just said don't do it unnecessarily.
